### ISSUE TITLE
Call a subroutine on a trigger

### ISSUE THREAD

**Issue by derek-adair** [sorc-lab/rodbot#1]
Use cases;

1. fleeing
2. bank runs
3. buff runs
4. etc

**Comment by macfisher** [comment]
Closing this issue as won't do. Subroutines can be customized via Mudlet triggers. This is already supported via Mudlet platform and does not need to be explicitly added to the source code. Bot code will eventually become more of a framework of API calls and less hard coded to do specific subroutines. In other words, the behavior will become more configurable. For now, use Mudlet triggers.
